name: build
on:
  workflow_dispatch:
  schedule:
    - cron: '33 12 * * *'
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  container:
    uses: greboid/.github/.github/workflows/checkout-build-and-push-docker.yml@master
    secrets: inherit
